server:
  port: ${AUTH_PORT}

spring:
  config:
    import:
      - application-jpa.yml
      - application-redis.yml
      - application-mail.yml
      - application-internal.yml
      - application-prometheus.yml
      - application-logging.yml