server:
  port: ${SERVER_PORT}

spring:
  config:
    import:
      - application-jpa.yml
      - application-redis.yml
      - application-mail.yml
      - application-internal.yml
      - application-prometheus.yml
      - application-logging.yml

email:
  authn:
    code-ttl: ${MAIL_AUTHN_CODE_TTL}
    status-ttl: ${MAIL_AUTHN_STATUS_TTL}